exclude: '^docs/conf.py'
default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: ["commit"]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=650']
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
  - id: no-commit-to-branch
    args: ['--branch', 'main']

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 22.3.0 #stable 0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ['--max-line-length=88', '--show-source']
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]

- repo: local
  hooks:
    - id: encryption-check
      name: Ansible Vault Encryption Check
      description: Checks that vault files are encrypted
      entry: /usr/local/bin/encryption-check.sh
      files: ((^|/)vault|vault.y[a]{0,1}ml$|.vault$)
      language: script
    - id: commit-msg
      name: conventional commit messages
      language: pygrep
      entry: '^(chore|test|feat|fix|build|docs|refactor)!?: ((?!.*(ing))(?!.*(ed))).*$'
      args: [--multiline, --negate]
      stages: [commit-msg]
