exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=650']
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows
  - id: no-commit-to-branch
    args: ['--branch', 'main']

## If you want to avoid flake8 errors due to unused vars or imports:
# - repo: https://github.com/myint/autoflake
#   rev: v1.4
#   hooks:
#   - id: autoflake
#     args: [
#       --in-place,
#       --remove-all-unused-imports,
#       --remove-unused-variables,
#     ]

# - repo: https://github.com/pycqa/isort
#   rev: 5.10.1
#   hooks:
#   - id: isort
- repo: local
  hooks:
    - id: isort
      name: isort
      entry: isort
      require_serial: true
      language: python
      language_version: python3
      types_or: [cython, pyi, python]
      args: ['--filter-files']
      minimum_pre_commit_version: '2.9.2'
      additional_dependencies: ['isort==5.10.1']
    - id: encryption-check
      name: Ansible Vault Encryption Check
      description: Checks that vault files are encrypted
      entry: /usr/local/bin/encryption-check.sh
      files: ((^|/)vault|vault.y[a]{0,1}ml$|.vault$)
      language: script

- repo: https://github.com/psf/black
  rev: 22.3.0 #stable 0
  hooks:
  - id: black
    language_version: python3

## If like to embrace black styles even in the docs:
# - repo: https://github.com/asottile/blacken-docs
#   rev: v1.12.0
#   hooks:
#   - id: blacken-docs
#     additional_dependencies: [black]

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ['--max-line-length=88']
  ## You can add flake8 plugins via `additional_dependencies`:
  #  additional_dependencies: [flake8-bugbear]
