name: Wtforglib Windows CI
# Run this job on pushes to `main`, and for pull requests. If you don't specify
# `branches: [main], then this actions runs _twice_ on pull requests, which is
# annoying.

on:
  push:
    branches: [windoze]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  windows:
    defaults:
      run:
        shell: bash
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']
        # python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Install dependencies
      run: |
        poetry run pip install -U pip
        poetry install

    # - name: Run mypy
    #   run: poetry run mypy wtforglib tests/**/*.py

    - name: Run flake8
      run: poetry run flake8 .

    - name: Run checks
      run: |
        poetry check
        poetry run pip check

    - name: Run pytest
      run: poetry run pytest tests
